name: 'Refined Cloudflare Pages Action'
description: 'Publish to Cloudflare Pages with PR previews'
author: AdrianGonz97
branding:
  color: orange
  icon: upload-cloud
inputs:
  apiToken:
    description: 'Cloudflare API Token'
    required: true
  accountId:
    description: 'Cloudflare Account ID'
    required: true
  projectName:
    description: 'The name of the Pages project to upload to'
    required: true
  directory:
    description: 'The build directory to upload'
    required: true
  githubToken:
    description: 'GitHub Token'
    required: true
  branch:
    description: 'The name of the branch you want to deploy to'
    required: false
  deploymentName:
    description: 'The name of the GitHub deployment'
    required: false
  workingDirectory:
    description: 'The working directory in which to run Wrangler'
    required: false
  wranglerVersion:
    description: 'The version of Wrangler to use'
    required: false
    default: '3'
runs:
  using: 'node20'
  main: 'dist/index.js'
outputs:
  id:
    description: 'The ID of the pages deployment'
  url:
    description: 'The URL of the pages deployment'
  alias:
    description: 'The alias, if it exists, otherwise the deployment URL'
  environment:
    description: 'The environment that was deployed to'
